name: Trigger-All-Workflows  # 主要工作流的名称

on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
    - cron: 0 20 * * 5  # 北京时间星期六凌晨4点，定时触发

jobs:
    Arthur-Athena-LiBwrt:
      uses: ./.github/workflows/Arthur&Athena-LiBwrt.yml

    Arthur-Athena-Roc:
      uses: ./.github/workflows/Arthur&Athena-Roc.yml
 
    Taiyi-LiBwrt:
      needs: Arthur-Athena-LiBwrt
      uses: ./.github/workflows/Taiyi-LiBwrt.yml

    Taiyi-Roc:
      needs: Arthur-Athena-Roc
      uses: ./.github/workflows/Taiyi-Roc.yml

    All-Clean:
      uses: ./.github/workflows/All-Clean.yml
